### ISSUE TITLE
Error: DatePickerTheme' isn't a function. 

### ISSUE THREAD

**Issue by AKovynev** [Realank/flutter_datetime_picker#316]
Today I am getting an error: 'DatePickerTheme' isn't a function.
Try correcting the name to match an existing function, or define a method or function named 'DatePickerTheme'.
![image](https://user-images.githubusercontent.com/118714968/217159024-01baaa19-12e8-4af1-b3c3-27a68ad1ba11.png)

**Comment by sarp86** [comment]
Any solutions? We should wait for fix?

**Comment by SerdarYildiz06** [comment]
It may seem irrelevant, but when I referenced the package from github, not pubdev, this problem was solved.

**Comment by SerdarYildiz06** [comment]
If my answer helped you can close the issue thanks @AKovynev

**Comment by TimestampWombat** [comment]
There is a conflict between the custom `DatePickerTheme` with flutter material package.
The solution is 
```
import 'package:flutter/material.dart' hide DatePickerTheme;
```

**Comment by ajayprakashshukla** [comment]
> It may seem irrelevant, but when I referenced the package from github, not pubdev, this problem was solved.

This didn't work out in my case, I still get the error.
I'm referencing the package as such : 

```
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master
```

**Comment by Anyitechs** [comment]
> > It may seem irrelevant, but when I referenced the package from github, not pubdev, this problem was solved.
> 
> This didn't work out in my case, I still get the error. I'm referencing the package as such :
> 
> ```
>   flutter_datetime_picker:
>     git:
>       url: https://github.com/Realank/flutter_datetime_picker.git
>       ref: master
> ```

I fixed this earlier internally. All I did was to rename the `DatePickerTheme` being imported from `'package:flutter_datetime_picker/src/datetime_picker_theme.dart'` as it's conflicting with Flutter's native `DatePickerTheme` function. Or you can refer to the fix on this [PR](https://github.com/Realank/flutter_datetime_picker/pull/330) that fixes the issue using aliases.

**Comment by rs-huypq** [comment]
You can try this
Change to this and use `dtpicker` or any name you want
```
import 'package:flutter_datetime_picker/flutter_datetime_picker.dart' as dtpicker;
```
After
```
dtpicker.DatePicker(...)
or
dtpicker.DatePickerTheme(...)
```
